### ISSUE TITLE
Add support of getDuration for Queries in Cosmos Diagnostics - V4 Java Cosmos SDK 

### ISSUE THREAD

**Issue by manishmsfte** [Azure/azure-cosmosdb-java#364] opened 2020-11-06 16:47 UTC
getDuration is part of Cosmos Diagnostics and provide latency information but it doesn't work for queries. Customers needed it in on priority.

**Comment by kushagraThapar** [comment] 2020-11-10 15:51
@manishmsfte - azure-cosmos V4 Java SDK has been relocated here : https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos
This issue is a duplicate of this feature issue which is in our backlog, please follow it here: https://github.com/Azure/azure-sdk-for-java/issues/12911

**Closed by kushagraThapar** 2020-11-10 15:51 UTC
