### ISSUE TITLE
Retry not happening with Direct mode

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-cosmosdb-java#263] opened 2019-09-30 13:27 UTC
While using latest v2.6.1 of SDK we are not seeing retry happening when Direct mode is used. Retry works as expected for Gateway mode.

Upon debugging it appears that `RequestRateTooLargeException` is getting created with statusCode 404 and hence ignored by `ResourceThrottleRetryPolicy`

https://github.com/Azure/azure-cosmosdb-java/blob/f8a1b4d7a67639dab5cf8e9a177c12558552381e/direct-impl/src/main/java/com/microsoft/azure/cosmosdb/internal/directconnectivity/rntbd/RntbdRequestManager.java#L824-L826

Can someone confirm if retry mode is supported for Direct mode

**Comment by kushagraThapar** [comment] 2019-09-30 19:42
@chetanmeh Thanks for capturing this, we will investigate this issue.

**Comment by David-Noble-at-work** [comment] 2019-10-10 23:53
Problem diagnosed and I'm reasonably confident the issue is addressed on branch danoble/issue-263/retry-not-happening. I fixed two definite issues and added test coverage to guard against regressions in the future:

* `RequestRateTooLargeException.getStatusCode` now correctly returns `TOO_MANY_REQUESTS`, not `NOTFOUND`.
* `ServiceUnavailableException.getStatusCode` now correctly returns `SERVICE_UNAVAILABLE`, not `NOTFOUND`.
* `DocuemntClientExceptionTest.statusCodeIsCorrect` verifies that the correct status code is returned for all DocumentClientException subtypes.

PR is pending.

**Comment by chetanmeh** [comment] 2019-10-11 04:23
@David-Noble-at-work Does the same issue exist in v3 SDK or there retry support work as expected?

**Comment by kushagraThapar** [comment] 2019-10-11 16:30
> @David-Noble-at-work Does the same issue exist in v3 SDK or there retry support work as expected?

It might, if that's the case we will confirm and port the fix to v3 as well.

**Comment by kushagraThapar** [comment] 2019-10-11 16:30
> Problem diagnosed and I'm reasonably confident the issue is addressed on branch danoble/issue-263/retry-not-happening. I fixed two definite issues and added test coverage to guard against regressions in the future:
> 
> * `RequestRateTooLargeException.getStatusCode` now correctly returns `TOO_MANY_REQUESTS`, not `NOTFOUND`.
> * `ServiceUnavailableException.getStatusCode` now correctly returns `SERVICE_UNAVAILABLE`, not `NOTFOUND`.
> * `DocuemntClientExceptionTest.statusCodeIsCorrect` verifies that the correct status code is returned for all DocumentClientException subtypes.
> 
> PR is pending.

Thank you David.

**Comment by kushagraThapar** [comment] 2019-10-12 04:11
This issue has been fixed in the PR: https://github.com/Azure/azure-cosmosdb-java/pull/272

We will release 2.6.3 with the fix.

**Closed by kushagraThapar** 2019-10-12 04:11 UTC
Labels: needs-investigation
